name: Daily Data Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch script
        run: python scripts/run_fetch_data.py

      - name: Commit and push data
        run: |
          git config --global user.name 'agron911'
          git config --global user.email 'agron911@gmail.com'
          git add data/
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push 