name: weekly Data Fetch

# 1) Grant the GITHUB_TOKEN write-access to this repo’s contents
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * 5,6'   # every Friday and Saturday at 00:00 UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout code with the default GITHUB_TOKEN
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: true   # <— this allows git push to use GITHUB_TOKEN

      # 3) (Optional) Debug: list all files
      - name: List repository contents
        run: |
          echo ">>> GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          ls -R $GITHUB_WORKSPACE

      # 4) Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 5) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6) Run your fetch script
      - name: Run fetch script
        run: |
          PYTHONPATH=$GITHUB_WORKSPACE \
            python scripts/run_fetch_data.py

      # 7) Commit & push any changes under data/
      - name: Commit and push data
        run: |
          git config --global user.name  'agron911'
          git config --global user.email 'agron911@gmail.com'
          git add -f data/
          git commit -m "Update data [skip ci]" || echo "No changes to commit"
          git push
